class Student:
    def __init__(self):
        self.student_name = input("\nEnter the student name: ")
        self.student_age = input("Enter the student age: ")
        self.student_gender = input("Enter the student gender: ")

    def display(self):
        print("Enter the student name: ",self.student_name)
        print("Enter the student age: ",self.student_age)
        print("Enter the student gender: ",self.student_gender)

class Marks:
    def __init__(self):
        self.grade = input("Enter the grade of the sudent: ")
        print("-----Evaluate marks per subject-----")
        self.mathematics = float(input("Marks in Mathematics subject: "))
        self.ict = float(input("Marks in ICT subject: "))
        self.socialscience = float(input("Marks in Social Science subject: "))
        self.science = float(input("Marks in Science subject: "))
        self.english = float(input("Marks in English subject: "))

    def display(self):
        self.total = self.mathematics + self.ict + self.socialscience + self.science + self.english
        print("Total Evaluated marks: ",self.total)

class Data(Student,Marks):
    def __init__(self):
        Student.__init__(self)
        Marks.__init__(self)

    def result(self):
        Marks.display(self)

S1 = Data()
S1.result()
S2 = Data()
S2.result()
S3 = Data()
S3.result()
S4 = Data()
S4.result()
S5 = Data()
S5.result()
S6 = Data()
S6.result()
S7 = Data()
S7.result()
S8 = Data()
S8.result()
S9 = Data()
S9.result()
S10 = Data()
S10.result()
S11 = Data()
S11.result()
S12 = Data()
S12.result()
S13 = Data()
S13.result()
S14 = Data()
S14.result()
S15 = Data()
S15.result()
S16 = Data()
S16.result()
S17 = Data()
S17.result()
S18 = Data()
S18.result()
S19 = Data()
S19.result()
S20 = Data()
S20.result()
S21 = Data()
S21.result()
S22 = Data()
S22.result()
S23 = Data()
S23.result()
S24 = Data()
S24.result()
S25 = Data()
S25.result()
S26 = Data()
S26.result()
S27 = Data()
S27.result()
S28 = Data()
S28.result()
S29 = Data()
S29.result()
S30 = Data()
S30.result()
S31 = Data()
S31.result()
S32 = Data()
S32.result()
S33 = Data()
S33.result()
S34 = Data()
S34.result()
S35 = Data()
S35.result()
S36 = Data()
S36.result()
S37 = Data()
S37.result()

print("You can create more objescts to add more studen data")
