lists=list(("hello","world"))
print(lists)

mylist=["pavie"]
mylist.append("Ananya")
print(mylist)
mylist.pop()
"Ananya"
print(mylist)
mylist.append("Ananya")
print(mylist)
mylist.reverse()
print(mylist)
mylist=["A","B","C","D"]
mylist.append(10)
mylist.append(8)
mylist.append(1)
mylist.append(7)
print(mylist)
